openapi: 3.0.1
info:
  contact: {}
  description: This is a sample server for a todo list.
  title: TodoList API
  version: "1.0"
servers:
- url: http://localhost:8081/
paths:
  /ping:
    get:
      description: Checks the health and responsiveness of the API server.
      operationId: pingGet
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: pong
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/models.ErrorResponse"
          description: Internal Server Error
      summary: Ping the server
      tags:
      - ping
  /v1/auth/login:
    post:
      description: "Authenticates a user with username and password, returning a JWT\
        \ token upon successful login."
      operationId: authLogin
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/models.User"
        description: User login credentials
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
          description: "Successful authentication, returns JWT token"
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/models.ErrorResponse"
          description: Bad Request - Invalid input or missing fields
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/models.ErrorResponse"
          description: Unauthorized - Invalid credentials
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/models.ErrorResponse"
          description: Internal Server Error - Failed to generate token
      summary: Login a user
      tags:
      - auth
      x-codegen-request-body-name: user
  /v1/auth/register:
    post:
      description: Registers a new user with a unique username and password. The password
        will be hashed before storage.
      operationId: authRegister
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/models.User"
        description: User registration details
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
          description: User created successfully
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/models.ErrorResponse"
          description: Bad Request - Invalid input or missing fields
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/models.ErrorResponse"
          description: Internal Server Error - Failed to hash password
      summary: Register a new user
      tags:
      - auth
      x-codegen-request-body-name: user
  /v1/todos:
    get:
      description: Retrieves a list of all todo items.
      operationId: todosGet
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/models.Todo"
                type: array
          description: List of todo items
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/models.ErrorResponse"
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Get all todos
      tags:
      - todos
    post:
      description: Creates a new todo item with the provided details.
      operationId: todosCreate
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/models.Todo"
        description: Todo item details
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/models.Todo"
          description: Newly created todo item
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/models.ErrorResponse"
          description: Bad Request - Invalid input or missing fields
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/models.ErrorResponse"
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Create a new todo
      tags:
      - todos
      x-codegen-request-body-name: todo
  /v1/todos/{id}:
    delete:
      description: Deletes a todo item by its ID.
      operationId: todosDelete
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        "204":
          content:
            application/json:
              schema:
                type: string
          description: Todo item deleted
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/models.ErrorResponse"
          description: Not Found - Todo item not found
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/models.ErrorResponse"
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Delete a todo
      tags:
      - todos
    get:
      description: Retrieves a single todo item by its ID.
      operationId: todosGetByID
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/models.Todo"
          description: Todo item found
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/models.ErrorResponse"
          description: Not Found - Todo item not found
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/models.ErrorResponse"
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Get a todo by ID
      tags:
      - todos
    put:
      description: Updates an existing todo item with the provided details.
      operationId: todosUpdate
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/models.Todo"
        description: Todo item details to update
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/models.Todo"
          description: Updated todo item
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/models.ErrorResponse"
          description: Bad Request - Invalid input or missing fields
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/models.ErrorResponse"
          description: Not Found - Todo item not found
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/models.ErrorResponse"
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Update an existing todo
      tags:
      - todos
      x-codegen-request-body-name: todo
components:
  schemas:
    models.ErrorResponse:
      example:
        code: 400
        message: Bad Request
      properties:
        code:
          example: 400
          type: integer
        message:
          example: Bad Request
          type: string
      type: object
    models.Todo:
      example:
        id: id
        title: title
        done: true
      properties:
        done:
          type: boolean
        id:
          type: string
        title:
          type: string
      type: object
    models.User:
      properties:
        password:
          type: string
        username:
          type: string
      type: object
x-original-swagger-version: "2.0"
